---
# tasks file for openvpn (Ubuntu specific)

- name: Install OpenVPN GPG key
  become: yes
  apt_key:
    id: '{{ openvpn_apt_signing_key }}'
    keyserver: hkps.pool.sks-keyservers.net
    state: present
  tags:
    - openvpn
  when: openvpn_apt_repo_distro != ""

- name: Add OpenVPN repository
  become: yes
  apt_repository:
    repo: 'deb http://build.openvpn.net/debian/openvpn/release/{{ openvpn_version }} {{ openvpn_apt_repo_distro }} main'
    state: present
  tags:
    - openvpn
  when: openvpn_apt_repo_distro != ""

- name: Install OpenVPN packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ openvpn_packages }}"
  tags:
    - openvpn

- name: Fix Xenial systemd service unit file
  become: yes
  template:
    src: openvpn@.service.j2
    dest: /lib/systemd/system/openvpn@.service
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == "xenial"
  notify:
    - reload systemd
  tags:
    - openvpn
